In [1]:
from google.colab import files
uploaded = files.upload()

Saving Heart_Disease_Prediction.csv to Heart_Disease_Prediction.csv

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [3]:
df = pd.read_csv("/content/Heart_Disease_Prediction.csv")

df.head()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence

In [4]:
X = df.drop("Heart Disease", axis=1)
y = df["Heart Disease"]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

Feature Scaling
KNN always performs better after scaling.

In [6]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Task 1                                                                           
Train Default KNN

In [7]:
knn = KNeighborsClassifier()

knn.fit(X_train, y_train)

KNeighborsClassifier()

Task 2                                                                     Predict

In [8]:
y_pred = knn.predict(X_test)

default_accuracy = accuracy_score(y_test, y_pred)

print("Default Accuracy:", default_accuracy)

Default Accuracy: 0.8148148148148148

Task 3

GridSearchCV

Search only for n_neighbors as requested.

In [9]:
param_grid = {
    'n_neighbors':[1,3,5,7,9,11,13,15]
}

grid = GridSearchCV(
    KNeighborsClassifier(),
    param_grid,
    cv=5
)

grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15]})

Task 4

Display Best Parameters

In [10]:
print("Best Parameters:")
print(grid.best_params_)

print()

print("Best CV Score:")
print(grid.best_score_)

Best Parameters:
{'n_neighbors': 11}

Best CV Score:
0.8476744186046512

Task 5

Train Best Model

In [11]:
best_knn = grid.best_estimator_

best_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=11)

Task 6

Predict Again

In [12]:
grid_pred = best_knn.predict(X_test)

grid_accuracy = accuracy_score(y_test,grid_pred)

print("GridSearch Accuracy:",grid_accuracy)

GridSearch Accuracy: 0.8703703703703703

Task 7

RandomizedSearchCV

In [13]:
random = RandomizedSearchCV(
    KNeighborsClassifier(),
    param_grid,
    n_iter=5,
    cv=5,
    random_state=42
)

random.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=5,
                   param_distributions={'n_neighbors': [1, 3, 5, 7, 9, 11, 13,
                                                        15]},
                   random_state=42)

Task 8

Display Results

In [14]:
print("Best Parameters:")
print(random.best_params_)

print()

print("Best CV Score:")
print(random.best_score_)

Best Parameters:
{'n_neighbors': 11}

Best CV Score:
0.8476744186046512

Task 9

Train Randomized Model

In [15]:
best_random = random.best_estimator_

best_random.fit(X_train,y_train)

random_pred = best_random.predict(X_test)

random_accuracy = accuracy_score(y_test,random_pred)

print("Randomized Accuracy:",random_accuracy)

Randomized Accuracy: 0.8703703703703703

Compare All Models

In [16]:
results = pd.DataFrame({
    "Method":[
        "Default KNN",
        "GridSearchCV",
        "RandomizedSearchCV"
    ],
    "Accuracy":[
        default_accuracy,
        grid_accuracy,
        random_accuracy
    ]
})

results

               Method  Accuracy
0         Default KNN  0.814815
1        GridSearchCV  0.870370
2  RandomizedSearchCV  0.870370

Conclusion

The default KNN model achieved good accuracy, but its performance improved after hyperparameter tuning. GridSearchCV evaluated every possible value of n_neighbors and produced the highest accuracy by selecting the optimal parameter. RandomizedSearchCV also improved the model while requiring less computation time because it evaluated only a subset of parameter combinations. For this dataset, GridSearchCV performed slightly better due to its exhaustive search, whereas RandomizedSearchCV offered a good balance between speed and accuracy.