Upload Dataset

In [1]:
from google.colab import files

uploaded = files.upload()

Saving Car_Price_Prediction.csv to Car_Price_Prediction.csv

Import Libraries

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

Load Dataset

In [3]:
df = pd.read_csv("Car_Price_Prediction.csv")

print("First 5 Rows")
display(df.head())

print("\nLast 5 Rows")
display(df.tail())

print("\nDataset Shape:")
print(df.shape)

print("\nDataset Information:")
df.info()

First 5 Rows

,Make,Model,Year,Engine Size,Mileage,Fuel Type,Transmission,Price
0,Honda,Model B,2015,3.9,74176,Petrol,Manual,30246.207931
1,Ford,Model C,2014,1.7,94799,Electric,Automatic,22785.747684
2,BMW,Model B,2006,4.1,98385,Electric,Manual,25760.290347
3,Honda,Model B,2015,2.6,88919,Electric,Automatic,25638.003491
4,Honda,Model C,2004,3.4,138482,Petrol,Automatic,21021.386657

Last 5 Rows

,Make,Model,Year,Engine Size,Mileage,Fuel Type,Transmission,Price
995,Toyota,Model D,2002,1.9,5445,Petrol,Manual,22765.597091
996,Honda,Model B,2020,3.1,149112,Diesel,Manual,30392.575567
997,Ford,Model C,2008,1.9,195387,Petrol,Automatic,16446.892292
998,Toyota,Model A,2003,4.4,246,Petrol,Automatic,27396.156708
999,Audi,Model C,2020,2.1,31153,Diesel,Automatic,31620.864907

Dataset Shape:
(1000, 8)

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Make          1000 non-null   object
 1   Model         1000 non-null   object
 2   Year          1000 non-null   int64
 3   Engine Size   1000 non-null   float64
 4   Mileage       1000 non-null   int64
 5   Fuel Type     1000 non-null   object
 6   Transmission  1000 non-null   object
 7   Price         1000 non-null   float64
dtypes: float64(2), int64(2), object(4)
memory usage: 62.6+ KB

Encode Categorical Columns

In [4]:
label_encoder = LabelEncoder()

categorical_columns = [
    "Make",
    "Model",
    "Fuel Type",
    "Transmission"
]

for column in categorical_columns:
    df[column] = label_encoder.fit_transform(df[column])

print(df.head())

   Make  Model  Year  Engine Size  Mileage  Fuel Type  Transmission  \
0     3      1  2015          3.9    74176          2             1
1     2      2  2014          1.7    94799          1             0
2     1      1  2006          4.1    98385          1             1
3     3      1  2015          2.6    88919          1             0
4     3      2  2004          3.4   138482          2             0

          Price
0  30246.207931
1  22785.747684
2  25760.290347
3  25638.003491
4  21021.386657

Select Features and Target

In [5]:
X = df.drop("Price", axis=1)
y = df["Price"]

print("Features (X)")
display(X)

print("\nTarget (y)")
display(y)

Features (X)

     Make  Model  Year  Engine Size  Mileage  Fuel Type  Transmission
0       3      1  2015          3.9    74176          2             1
1       2      2  2014          1.7    94799          1             0
2       1      1  2006          4.1    98385          1             1
3       3      1  2015          2.6    88919          1             0
4       3      2  2004          3.4   138482          2             0
..    ...    ...   ...          ...      ...        ...           ...
995     4      3  2002          1.9     5445          2             1
996     3      1  2020          3.1   149112          0             1
997     2      2  2008          1.9   195387          2             0
998     4      0  2003          4.4      246          2             0
999     0      2  2020          2.1    31153          0             0

[1000 rows x 7 columns]

Target (y)

0      30246.207931
1      22785.747684
2      25760.290347
3      25638.003491
4      21021.386657
           ...
995    22765.597091
996    30392.575567
997    16446.892292
998    27396.156708
999    31620.864907
Name: Price, Length: 1000, dtype: float64

Train-Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (800, 7)
Testing Data Shape: (200, 7)

Train the Model

In [7]:
model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

Make Predictions

In [8]:
predictions = model.predict(X_test)

print("First 10 Predicted Prices:")
print(predictions[:10])

print("\nFirst 10 Actual Prices:")
print(y_test.values[:10])

First 10 Predicted Prices:
[25852.90025977 29463.01030036 27562.63414635 26058.01481113
 28182.7741229  19396.36694511 22475.22865133 27231.43086778
 30625.12380026 22799.67715766]

First 10 Actual Prices:
[27902.28787922 30526.27286293 26754.65072442 28641.33635829
 28425.17326959 16987.76175985 23731.53326253 29634.11708368
 33056.12686375 22252.25095286]

Predict New Cars

In [9]:
new_cars = pd.DataFrame({
    "Make": [2, 1, 0],
    "Model": [0, 1, 2],
    "Year": [2022, 2019, 2021],
    "Engine Size": [2.0, 1.8, 3.0],
    "Mileage": [15000, 35000, 10000],
    "Fuel Type": [2, 0, 1],
    "Transmission": [0, 1, 0]
})

new_predictions = model.predict(new_cars)

print("Predicted Prices for New Cars:")
print(new_predictions)

Predicted Prices for New Cars:
[29765.79482986 31439.07859476 34720.35706575]

Model Evaluation

In [10]:
mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("Mean Absolute Error:", mae)
print("R² Score:", r2)

Mean Absolute Error: 1924.2364209581356
R² Score: 0.793778893136633

Summary

In [11]:
print("========== PROJECT SUMMARY ==========")
print("Dataset Name      : Car Price Prediction")
print("Number of Records :", df.shape[0])
print("Number of Features:", X.shape[1])
print("Target Column     : Price")
print("Model Used        : RandomForestRegressor")

========== PROJECT SUMMARY ==========
Dataset Name      : Car Price Prediction
Number of Records : 1000
Number of Features: 7
Target Column     : Price
Model Used        : RandomForestRegressor